pipeline {
    agent any

    environment {
        DOCKER_HUB_USER = 'mdmastan222'              
        BACKEND_IMAGE = "${DOCKER_HUB_USER}/genius-backend"
        FRONTEND_IMAGE = "${DOCKER_HUB_USER}/genius-frontend"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Mastan-CloudOps/Edtech-App.git'
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('backend-flask-pythonRestAPI') {
                    script {
                        docker.build("${BACKEND_IMAGE}:latest")
                    }
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('Frontend-React-SimpleUI') {
                    script {
                        docker.build("${FRONTEND_IMAGE}:latest")
                    }
                }
            }
        }

        stage('Push Images to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',   
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${BACKEND_IMAGE}:latest
                        docker push ${FRONTEND_IMAGE}:latest
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Backend & Frontend images pushed to DockerHub successfully!"
        }
        failure {
            echo "Pipeline failed. Check logs."
        }
    }
}

